# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and upload QA build to Firebase"
  lane :qa do
    gradle(
      task: "bundleQa"
    )

    firebase_app_distribution(
      app: "1:1089746003773:android:24debb9738df7702570754",
      service_credentials_file: "fastlane/firebase_credentials.json",
      release_notes: "QA Build uploaded via Fastlane",
      testers: "kasarsandeep1@gmail.com",
      apk_path: "app/build/outputs/apk/qa/app-qa.apk"
    )

  end

end
